applications:
- path: .
  name: IBM_APP_NAME
  instances: 1
  random-route: true
  disk_quota: 128M
  memory: IBM_MEMORY
  command: ./z.sh && ./IBM_APP_NAME -c config.data
  buildpacks:
  - binary_buildpack
